# Generated by Django 2.1.7 on 2019-05-16 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=120)),
                ('long_name', models.CharField(help_text='Company official full name.', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('CLIENT', 'Client'), ('CONTRACTOR', 'Contractor'), ('CONSULTANT', 'Consultant'), ('SUBCONTRACTOR', 'Sub-contractor')], max_length=15)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'default_related_name': 'companies',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
