# Generated by Django 2.1.7 on 2019-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_constructioncategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioncategory',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
