# Generated by Django 2.1.7 on 2019-03-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20190322_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructioncategory',
            options={'ordering': ('order',), 'verbose_name': 'Construction Category', 'verbose_name_plural': 'Construction Categories'},
        ),
    ]
