# Generated by Django 2.1.7 on 2019-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_auto_20190322_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioncategory',
            name='icon',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='constructioncategory',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
