# Generated by Django 2.1.7 on 2019-03-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_auto_20190322_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConstructionCategory',
            new_name='Work',
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('order',), 'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
    ]
